# Shopify App Configuration
# Learn more: https://shopify.dev/docs/apps/tools/cli/configuration

name = "Onsite Commission Engine"
client_id = "2c0c2d3236620126da1b4b8ab6ce01af"
application_url = "https://shopify-app-q4bw.onrender.com"

[access_scopes]
scopes = "read_all_orders,read_customers,read_products,read_script_tags,write_script_tags"

[auth]
redirect_urls = [
  "https://your-app-url.com/auth/callback",
  "https://your-app-url.com/auth/shopify/callback",
  "https://your-app-url.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://your-app-url.com/webhooks/customers/delete"
  customer_data_request_url = "https://your-app-url.com/webhooks/customers/data-request"
  shop_deletion_url = "https://your-app-url.com/webhooks/shop/delete"

[app_proxy]
url = "https://your-app-url.com/proxy"
subpath = "oce"
prefix = "apps"

[pos]
embedded = false

[[extensions]]
name = "OCE Script Tag"
type = "theme"
handle = "oce-script-tag"
