api_version = "2024-10"

[[extensions]]
name = "OCE Test Video Player"
type = "theme"
handle = "oce-test-player"

  [[extensions.blocks]]
  name = "Test Video Player"
  type = "video-player"
  target = "section"
